[[query-dsl-range-query]]
=== Range Query

匹配文档的字段的词在特定的范围内。Lucene查询的类型取决于字段的类型，
对于字符串字段，范围查询是 `TermRangeQuery`，而对于数字或者日期字段，
范围查询是 `NumericRangeQuery`。下面的示例返回年龄在10到20岁之间的所有文档：

[source,js]
--------------------------------------------------
GET _search
{
    "query": {
        "range" : {
            "age" : {
                "gte" : 10,
                "lte" : 20,
                "boost" : 2.0
            }
        }
    }
}
--------------------------------------------------
// CONSOLE

范围查询接受以下参数：

[horizontal]
`gte`:: 	大于或等于
`gt`::  	大于
`lte`:: 	小于或等于
`lt`::  	小于
`boost`:: 	设置查询的权重值，默认为 `1.0`


[[ranges-on-dates]]
==== 日期字段范围

当在 <<date,`日期`>> 类型的字段上运行 `范围` 查询时，可以使用 <<date-math>> 指定范围：

[source,js]
--------------------------------------------------
GET _search
{
    "query": {
        "range" : {
            "date" : {
                "gte" : "now-1d/d",
                "lt" :  "now/d"
            }
        }
    }
}
--------------------------------------------------
// CONSOLE

===== 日期数学表达和舍入

使用 <<date-math,date math>> 将日期舍入到最近的日，月份，小时等时，
舍入的日期取决于范围的结尾是包含还是排除。

向上舍入是取舍入范围的最后一毫秒，向下舍入是取舍入范围的第一毫秒。例如：

[horizontal]
`gt`::

    大于日期，向上舍入：`2014-11-18||/M` 变为 `2014-11-30T23:59:59.999`，
    即不包含整个11月。

`gte`::

    大于等于日期，向下舍入：`2014-11-18||/M` 变为 `2014-11-01`，即包含整个11月。

`lt`::

    小于日期，向下舍入：`2014-11-18||/M` 变为 `2014-11-01`，即不包含整个11月。

`lte`::

    小于等于日期，向上舍入：`2014-11-18||/M` 变为 `2014-11-30T23:59:59.999`，
    即包含整个11月。

===== 范围查询中的日期格式化

对范围查询格式化日期时，将默认使用 <<date,`date`>> 字段中指定的
<<mapping-date-format,`format`>> 进行解析，当然也可以通过 `format` 参数来覆盖默认的设置。

[source,js]
--------------------------------------------------
GET _search
{
    "query": {
        "range" : {
            "born" : {
                "gte": "01/01/2012",
                "lte": "2013",
                "format": "dd/MM/yyyy||yyyy"
            }
        }
    }
}
--------------------------------------------------
// CONSOLE

注意：如果日期缺失了年，月和日中的部分，缺失的部分将被填充为
https://en.wikipedia.org/wiki/Unix_time[unix time] 的初始值，也就是1970年1月1日。
这意味着，将 `dd` 指定为格式时，像 `"gte" : 10` 将转换为 `1970-01-10T00:00:00.000Z`。

===== 范围查询中的时区

可以在日期值本身（如果是  <<mapping-date-format, `format`>> 中可接受的格式）中指定时区，
将日期从另一个时区转换为UTC时间，或者也可以指定 `time_zone` 参数：

[source,js]
--------------------------------------------------
GET _search
{
    "query": {
        "range" : {
            "timestamp" : {
                "gte": "2015-01-01 00:00:00", <1>
                "lte": "now", <2>
                "time_zone": "+01:00"
            }
        }
    }
}
--------------------------------------------------
// CONSOLE
<1> 这个日期将被转换为 `2014-12-31T23:00:00 UTC`。
<2> `now` 是不受 `time_zone` 参数影响的（日期必须存储为UTC时间）。

[[querying-range-fields]]
==== 查询范围字段

`range` 查询可用于 <<range,`range`>> 类型的字段，允许将查询中指定的范围与文档中的范围字段匹配，
 `relation` 参数控制如何匹配两个范围：

[horizontal]
`WITHIN`::

    匹配范围字段完全在查询范围内的文档。

`CONTAINS`::

    匹配范围字段完全包含查询范围的文档。

`INTERSECTS`::

    匹配范围字段和查询范围相交的文档。
    这是查询范围字段时的默认值。

有关示例，请参见 <<range,`range`>> 映射类型。
